### PR TITLE
More dynamic rendering draw time VUIDs and tests

### PR DESCRIPTION
**Pull request by stu-s**
Add VUIDs for:
    VUID-vkCmdDraw-pDepthAttachment-06181
    VUID-vkCmdDraw-pStencilAttachment-06182

Moved VUID for:
    VUID-vkCmdDraw-colorAttachmentCount-06188

Fixes for dynamic rendering with sample count structure

Added tests for:
    VUID-vkCmdDraw-viewMask-06178
    VUID-vkCmdDraw-colorAttachmentCount-06179
    VUID-vkCmdDraw-colorAttachmentCount-06180
    VUID-vkCmdDraw-pDepthAttachment-06181
    VUID-vkCmdDraw-pStencilAttachment-06182
    VUID-vkCmdDraw-colorAttachmentCount-06185
    VUID-vkCmdDraw-pDepthAttachment-06186
    VUID-vkCmdDraw-pStencilAttachment-06187
    VUID-vkCmdDraw-colorAttachmentCount-06188
    VUID-vkCmdDraw-pDepthAttachment-06189
    VUID-vkCmdDraw-pStencilAttachment-06190

### CODE REVIEW

**Comment by stu-s** [comment]
@AaronHaganAMD Can you double-check two of the VUID changes, please?
- I've added what I thought were missing VUIDs to drawdispatch.cpp - are they missing, or intentionally left out?
- I moved the check for dynamic_rendering_multi_sample outside of the attachment_sample_count_info_xxx check as it looked like it was in the wrong place

**Comment by AaronHaganAMD** [comment]
> * were missing VUIDs to drawdispatch.cpp - were they missing, or intentionally left out?
> * I moved the check for dynamic_rendering_multi_sample outside of the attachment_sample_count_info_xxx check as it looked like it was in the wrong place
> * I've also changed a few places using pPipeline->create_info.graphics.pMultisampleState->rasterizationSamples to GetNumSamples() as I _think_ that's safer

These changes look good to me

**Comment by stu-s** [comment]
> CI Vulkan-ValidationLayers build # 5838 failed.

@ncesario-lunarg is there any way for me to see what's going wrong with the build?

**Comment by ncesario-lunarg** [comment]
Sorry for the delayed response @stu-s. If you have an email associated with your github account, you should get an email from `ci-tester-lunarg` containing the results from our CI run. I would rebase on top of ToT as there were some errors on linux that should be resolved in the latest changes on master.

**Comment by stu-s** [comment]
> Sorry for the delayed response @stu-s. If you have an email associated with your github account, you should get an email from `ci-tester-lunarg` containing the results from our CI run. I would rebase on top of ToT as there were some errors on linux that should be resolved in the latest changes on master.

Unfortunately, the email contents appear to be just "CI Vulkan-ValidationLayers build # 5838 failed."

I'll rebase and see if that improves things

**Comment by ncesario-lunarg** [comment]
Yeah, that one unfortunately won't contain any logs (I don't think @lunarpapillo?).

The failure is a single test on nvidia hardware:
```
[ RUN      ] VkLayerTest.CommandDrawDynamicRendering
Unexpected: Validation Error: [ VUID-vkCmdDraw-pStencilAttachment-06182 ] Object 0: handle = 0x1a141f78, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x17a12692 | vkCmdDraw: Stencil attachment imageView format (VK_FORMAT_D32_SFLOAT_S8_UINT) must match corresponding format in pipeline (VK_FORMAT_UNDEFINED) The Vulkan spec states: If the current render pass instance was begun with vkCmdBeginRenderingKHR and VkRenderingInfoKHR::pStencilAttachment->pname:imageView was not VK_NULL_HANDLE, the value of VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat used to create the currently bound graphics pipeline must be equal to the VkFormat used to create VkRenderingInfoKHR::pStencilAttachment->pname:imageView (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-pStencilAttachment-06182)
C:\j\w\32-bit\Release\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
```

**Comment by stu-s** [comment]
> Yeah, that one unfortunately won't contain any logs (I don't think @lunarpapillo?).
> 
> The failure is a single test on nvidia hardware:
> 
> ```
> [ RUN      ] VkLayerTest.CommandDrawDynamicRendering
> Unexpected: Validation Error: [ VUID-vkCmdDraw-pStencilAttachment-06182 ] Object 0: handle = 0x1a141f78, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x17a12692 | vkCmdDraw: Stencil attachment imageView format (VK_FORMAT_D32_SFLOAT_S8_UINT) must match corresponding format in pipeline (VK_FORMAT_UNDEFINED) The Vulkan spec states: If the current render pass instance was begun with vkCmdBeginRenderingKHR and VkRenderingInfoKHR::pStencilAttachment->pname:imageView was not VK_NULL_HANDLE, the value of VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat used to create the currently bound graphics pipeline must be equal to the VkFormat used to create VkRenderingInfoKHR::pStencilAttachment->pname:imageView (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-pStencilAttachment-06182)
> C:\j\w\32-bit\Release\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
> ```

Thanks. I've fixed the test.

**Comment by stu-s** [comment]
I'm not sure what's happening for the Linux check failures.  They seem unrelated to my changes, and each one looks like a different test crashing  (VkLayerTest.MultiplaneImageLayoutBadAspectFlags, VkLayerTest.InvalidSignalSemaphoreType, VkLayerTest.PipelineSubgroupSizeControl)

**Comment by stu-s** [comment]
The Linux check failures look similar to those in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3659

**Review by ncesario-lunarg — APPROVED** [review]
Thanks for the changes @stu-s! The linux failures should be addressed by rebasing on to ToT (fixed in #3679).

**Comment by stu-s** [comment]
> Thanks for the changes @stu-s! The linux failures should be addressed by rebasing on to ToT (fixed in #3679).

Thanks. That's fixed the failures.
