### ISSUE TITLE
Fails to build with Clang 13 (due to -Werror)

### ISSUE THREAD

**Issue by jbeich** [KhronosGroup/Vulkan-ValidationLayers#3520]
Regressed by https://github.com/llvm/llvm-project/commit/abf3ca61e3235. Workaround is `-DBUILD_WERROR=OFF`.

```c++
$ export CC=clang13 CXX=clang++13
$ cmake -B /tmp/build -G Ninja
$ cmake --build /tmp/build
[...]
In file included from layers/core_validation.cpp:70:
In file included from layers/core_validation.h:31:
In file included from layers/image_layout_map.h:30:
layers/subresource_adapter.h:67:5: error: definition of implicit copy assignment operator for 'Subresource' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    Subresource(const Subresource& from) = default;
    ^
layers/subresource_adapter.h:305:42: note: in implicit copy assignment operator for 'subresource_adapter::Subresource' first required here
        *static_cast<Subresource*>(this) = encoder_->Decode(index);
                                         ^
1 error generated.
```
http://www.ipv6proxy.net/go.php?u=http://gohan04.nyi.freebsd.org/data/mainamd64PR258209-default/2021-10-16_18h41m03s/logs/errors/vulkan-validation-layers-1.2.196.log

**Comment by ncesario-lunarg** [comment]
Thanks @jbeich, I briefly tried out clang 13 and saw this same error. Are you saying this is a bug in llvm? Setting `-DBUILD_WERROR=OFF` can't be checked in. We could disable that specific warning, but it would be better if we can just fix the warning if it is valid.

**Comment by jbeich** [comment]
> Are you saying this is a bug in llvm?

No, an intentional change by Clang. This repo uses `-Werror` applied to all warnings rather than a specific subset, so every compiler upgrade (including GCC) may cause regressions.

**Comment by ncesario-lunarg** [comment]
> This repo uses -Werror applied to -Wall + -Wextra instead of a static subset (e.g., -Werror=uninitialized, -Werror=return-type), so every compiler upgrade (including GCC) may cause regressions due to new warnings.

While I can see the merits of a "static approach," for this particular code base, I believe this is by design. Barring compiler bugs (which we are counting on effecting us relatively infrequently), I think the assumption is that we would like to know about new warnings as they show up, and then fix them if they are valid, or disable them if they are not.
