### PR TITLE
build: Update glslang to latest

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**

### CODE REVIEW

**Review by spencer-lunarg — APPROVED** [review]

**Comment by jeremyg-lunarg** [comment]
This test is failing everywhere:
```
[ RUN      ] PositiveShaderInterface.PackingInsideArray
ERROR: 0:4: 'location' : the aliases sharing the location 1 must be the same basic type and interpolation qualification
ERROR: 1 compilation errors.  No code generated.
```

**Comment by jeremyg-lunarg** [comment]
Most likely caused by https://github.com/KhronosGroup/glslang/pull/3438 @spencer-lunarg can you please take a look at if this commit is right or your test and gitlab issue are?
