### ISSUE TITLE
Build failure on MIPS

### ISSUE THREAD

**Issue by AdrianBunk** [KhronosGroup/Vulkan-ValidationLayers#3607]
In Debian on MIPS (32bit and 64bit, only little endian tested but the problem should also be present on big endian):

https://buildd.debian.org/status/fetch.php?pkg=vulkan-validationlayers&arch=mips64el&ver=1.2.189.0-1.1&stamp=1633569889&raw=0
```
/<<PKGBUILDDIR>>/layers/best_practices_utils.cpp: In member function ‘IMAGE_STATE_BP* BestPractices::GetImageUsageState(VkImage)’:
/<<PKGBUILDDIR>>/layers/best_practices_utils.cpp:390:20: error: expected unqualified-id before numeric constant
  390 |         for (auto& mips : state.usages) {
      |                    ^~~~
/<<PKGBUILDDIR>>/layers/best_practices_utils.cpp:390:19: error: expected ‘;’ before numeric constant
  390 |         for (auto& mips : state.usages) {
      |                   ^
      |                   ;
/<<PKGBUILDDIR>>/layers/best_practices_utils.cpp:390:25: error: expected ‘;’ before ‘:’ token
  390 |         for (auto& mips : state.usages) {
      |                         ^
```

This is due to:
```
$ gcc -dM -E - < /dev/null | grep " mips "
#define mips 1
```

Renaming ``mips`` to ``mymips`` or whatever name you consider appropriate fixes it.

**Comment by AdrianBunk** [comment]
@ZandroFargnoli This issue was introduced in commit 1ced2b6abd

**Comment by ncesario-lunarg** [comment]
Wow, that is unfortunate. Would adding the following at the top of the cpp file work, or potentially cause other problems?
```cpp
#ifdef mips
#undef mips
#endif
```

**Comment by AdrianBunk** [comment]
Some header might be checking it, so yes this might potentially cause other problems.

It is a local variable with tiny scope, so renaming it should not cause too much pain:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/best_practices_utils.cpp#L379-L381

**Comment by ncesario-lunarg** [comment]
I agree a rename is trivial, but `mips` isn't exactly an outlandish variable name. I'm surprised GCC defines this without any `__` prefix/suffix. Is it possible this definition is coming from somewhere else?

**Comment by AdrianBunk** [comment]
> I agree a rename is trivial, but `mips` isn't exactly an outlandish variable name.

``alpha``, ``pixel`` or ``vector`` (the latter two for AltiVec) are also not outlandish variable names but defined on other architectures.

> I'm surprised GCC defines this without any `__` prefix/suffix.

gcc also defines ``_mips``, ``__mips`` and ``__mips__``.
From a namespace point of view ``mips`` is wrong, but that's compatibility with a mistake three decades ago when people were less aware of such issues.

> Is it possible this definition is coming from somewhere else?

No, as said it is in
```
gcc -dM -E - < /dev/null
```

**Comment by ziga-lunarg** [comment]
I don't see `mips` being used anymore, @AdrianBunk can you verify this issue is resolved?

**Comment by AdrianBunk** [comment]
> I don't see `mips` being used anymore, @AdrianBunk can you verify this issue is resolved?

Yes, it seems this was implicitly fixed by commit 20da7a1996c478240c54a76ee6bf68b310b14a19
