### ISSUE TITLE
[regression] VK_USE_PLATFORM_MACOS_MVK not defined!

### ISSUE THREAD

**Issue by SoltiGG** [KhronosGroup/Vulkan-ValidationLayers#6780]
**Environment:**
 - OS: Mac
 - GPU and driver version: Intel

ANGLE on Mac builds failed after merging https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b3b70e9a7117170bb994f0087ea90f8acdcad92e

can you advice how to fix this?

### build error log:
```
../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/vk_layer_config.cpp:438:2: error: "VK_USE_PLATFORM_MACOS_MVK not defined!"
  438 | #error "VK_USE_PLATFORM_MACOS_MVK not defined!"
      |  ^
1 error generated.
ninja: build stopped: subcommand failed. 
```

**Comment by spencer-lunarg** [comment]
thanks for raising @SoltiGG , @juan-lunarg has the Mac setup locally so he will get a fix in

**Comment by juan-lunarg** [comment]
Looks like all the VK_USE_PLATFORM defines are done in Vulkan-Headers and propogated to VVL. So the fix will be made in that repo.
