### PR TITLE
build: Fix deprecated-copy warnings in clang 13

### LINKED ISSUE #3520: Fails to build with Clang 13 (due to -Werror)
Regressed by https://github.com/llvm/llvm-project/commit/abf3ca61e3235. Workaround is `-DBUILD_WERROR=OFF`.

```c++
$ export CC=clang13 CXX=clang++13
$ cmake -B /tmp/build -G Ninja
$ cmake --build /tmp/build
[...]
In file included from layers/core_validation.cpp:70:
In file included from layers/core_validation.h:31:
In file included from layers/image_layout_map.h:30:
layers/subresource_adapter.h:67:5: error: definition of implicit copy assignment operator for 'Subresource' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    Subresource(const Subresource& from) = default;
    ^
layers/subresource_adapter.h:305:42: note: in implicit copy assignment operator for 'subresource_adapter::Subresource' first required here
        *static_cast<Subresource*>(this) = encoder_->Decode(index);
                                         ^
1 error generated.
```
http://www.ipv6proxy.net/go.php?u=http://gohan04.nyi.freebsd.org/data/mainamd64PR258209-default/2021-10-16_18h41m03s/logs/errors/vulkan-validation-layers-1.2.196.log

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Starting in C++11, the use of the default copy constructor and
assignment operator is deprecated. The fix is to make the use of the
default copy constructor and assignment operator explicit.

Closes #3520.

### CODE REVIEW

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM.

**Review by jzulauf-lunarg — APPROVED** [review]
Looks clean.
