### ISSUE TITLE
Build fails because of a compilation error.

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-ValidationLayers#5473]
**Environment:**
 - OS: Ubuntu 18.04
 - SDK or header version if building from repo: main

**Describe the Issue**

Build fails with the message:

```
Vulkan-ValidationLayers/layers/./utils/vk_layer_utils.h: In function ‘constexpr VkExtent3D GetEffectiveExtent(const VkImageCreateInfo&, VkImageAspectFlags, uint32_t)’:
Vulkan-ValidationLayers/layers/./utils/vk_layer_utils.h:415:27: error: call to non-constexpr function ‘bool FormatIsMultiplane(VkFormat)’
     if (FormatIsMultiplane(format)) {
```

**Comment by juan-lunarg** [comment]
Strange how this isn't failing CI. Because that error message is completely valid.

**Comment by juan-lunarg** [comment]
@nikitablack would you have an idea as to why our current CI isn't showing this issue?

**Comment by nikitablack** [comment]
@juan-lunarg no, sorry, I have no idea how you CI is set up and running.

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/8b4a4eb257f88e69eadbf30974680bf8cb6d9b84/.github/workflows/vvl.yml#L33-L39

We currently test both GCC/Clang builds with warnings as errors on Ubuntu 22.04
