### ISSUE TITLE
Compilation failure with the latest Vulkan headers

### ISSUE THREAD

**Issue by vonture** [KhronosGroup/Vulkan-ValidationLayers#2525]
**Describe the Issue**
When compiling Vulkan-ValidationLayers with the latest Vulkan-Headers, an updated macro causes compilation errors in the validation layers:

vk_extension_helper.h:902:28: error: use of undeclared identifier 'VK_QCOM_rotated_copy_commands_EXTENSION_NAME'
            std::make_pair(VK_QCOM_rotated_copy_commands_EXTENSION_NAME, DeviceInfo(&DeviceExtensions::vk_qcom_rotated_copy_commands, {{

vk_extension_helper.h:1218:5: error: use of undeclared identifier 'VK_QCOM_rotated_copy_commands_EXTENSION_NAME'
    VK_QCOM_rotated_copy_commands_EXTENSION_NAME,

This regressed in https://github.com/KhronosGroup/Vulkan-Headers/commit/ec2db85225ab410bc6829251bef6c578aaed5868

**Comment by shannon-lunarg** [comment]
This should have been addressed in #2531. If you are still seeing this error or similar after building the latest VVL, you can reopen this issue. Thanks!
